<?php

namespace Database\Seeders;

use App\Models\Produk;
use Illuminate\Database\Seeder;

class ProdukSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $produks = [
            [
                'kode_produk' => 'PRD-001',
                'nama_produk' => 'Sepatu Pantofel Pria Kulit',
                'ukuran' => '40',
                'warna' => 'Hitam',
                'harga_jual' => 750000.00,
                'stok' => 25,
                'minimum_stok' => 5,
                'bom_category_id' => null,
            ],
            [
                'kode_produk' => 'PRD-002',
                'nama_produk' => 'Sepatu Sneakers Casual Pria',
                'ukuran' => '41',
                'warna' => 'Putih',
                'harga_jual' => 450000.00,
                'stok' => 40,
                'minimum_stok' => 10,
                'bom_category_id' => null,
            ],
            [
                'kode_produk' => 'PRD-003',
                'nama_produk' => 'Sepatu Oxford Formal',
                'ukuran' => '42',
                'warna' => 'Cokelat',
                'harga_jual' => 850000.00,
                'stok' => 15,
                'minimum_stok' => 5,
                'bom_category_id' => null,
            ],
            [
                'kode_produk' => 'PRD-004',
                'nama_produk' => 'Sandal Kulit Pria',
                'ukuran' => '39',
                'warna' => 'Tan',
                'harga_jual' => 350000.00,
                'stok' => 60,
                'minimum_stok' => 15,
                'bom_category_id' => null,
            ],
            [
                'kode_produk' => 'PRD-005',
                'nama_produk' => 'Sepatu Boots Safety Kerja',
                'ukuran' => '43',
                'warna' => 'Hitam',
                'harga_jual' => 950000.00,
                'stok' => 10,
                'minimum_stok' => 3,
                'bom_category_id' => null,
            ],
            [
                'kode_produk' => 'PRD-006',
                'nama_produk' => 'Sepatu Loafer Pria Slip-On',
                'ukuran' => '41',
                'warna' => 'Cokelat',
                'harga_jual' => 650000.00,
                'stok' => 20,
                'minimum_stok' => 5,
                'bom_category_id' => null,
            ],
            [
                'kode_produk' => 'PRD-007',
                'nama_produk' => 'Sepatu Derby Kulit Formal',
                'ukuran' => '40',
                'warna' => 'Navy',
                'harga_jual' => 800000.00,
                'stok' => 12,
                'minimum_stok' => 3,
                'bom_category_id' => null,
            ],
            [
                'kode_produk' => 'PRD-008',
                'nama_produk' => 'Sepatu Brogue Klasik',
                'ukuran' => '42',
                'warna' => 'Tan',
                'harga_jual' => 900000.00,
                'stok' => 8,
                'minimum_stok' => 3,
                'bom_category_id' => null,
            ],
            [
                'kode_produk' => 'PRD-009',
                'nama_produk' => 'Sepatu Kulit Moccasin',
                'ukuran' => '41',
                'warna' => 'Cokelat',
                'harga_jual' => 700000.00,
                'stok' => 18,
                'minimum_stok' => 5,
                'bom_category_id' => null,
            ],
            [
                'kode_produk' => 'PRD-010',
                'nama_produk' => 'Sepatu Chelsea Boots Pria',
                'ukuran' => '40',
                'warna' => 'Hitam',
                'harga_jual' => 1100000.00,
                'stok' => 10,
                'minimum_stok' => 3,
                'bom_category_id' => null,
            ],
            [
                'kode_produk' => 'PRD-011',
                'nama_produk' => 'Sepatu Boots Casual Kulit',
                'ukuran' => '43',
                'warna' => 'Navy',
                'harga_jual' => 1000000.00,
                'stok' => 15,
                'minimum_stok' => 5,
                'bom_category_id' => null,
            ],
            [
                'kode_produk' => 'PRD-012',
                'nama_produk' => 'Sepatu Kulit Premium Handmade',
                'ukuran' => '40',
                'warna' => 'Hitam',
                'harga_jual' => 1500000.00,
                'stok' => 5,
                'minimum_stok' => 3,
                'bom_category_id' => null,
            ],
            [
                'kode_produk' => 'PRD-013',
                'nama_produk' => 'Sepatu Sneakers Kulit Casual',
                'ukuran' => '41',
                'warna' => 'Putih',
                'harga_jual' => 850000.00,
                'stok' => 22,
                'minimum_stok' => 5,
                'bom_category_id' => null,
            ],
            [
                'kode_produk' => 'PRD-014',
                'nama_produk' => 'Sandal Formal Kulit',
                'ukuran' => '42',
                'warna' => 'Tan',
                'harga_jual' => 400000.00,
                'stok' => 50,
                'minimum_stok' => 10,
                'bom_category_id' => null,
            ],
            [
                'kode_produk' => 'PRD-015',
                'nama_produk' => 'Sepatu Oxford Semi Kulit',
                'ukuran' => '39',
                'warna' => 'Cokelat',
                'harga_jual' => 550000.00,
                'stok' => 28,
                'minimum_stok' => 8,
                'bom_category_id' => null,
            ],
            [
                'kode_produk' => 'PRD-016',
                'nama_produk' => 'Sepatu Pantofel Hitam Formal',
                'ukuran' => '43',
                'warna' => 'Hitam',
                'harga_jual' => 680000.00,
                'stok' => 33,
                'minimum_stok' => 8,
                'bom_category_id' => null,
            ],
            [
                'kode_produk' => 'PRD-017',
                'nama_produk' => 'Sepatu Boots Tinggi Kulit',
                'ukuran' => '42',
                'warna' => 'Cokelat',
                'harga_jual' => 1200000.00,
                'stok' => 7,
                'minimum_stok' => 3,
                'bom_category_id' => null,
            ],
            [
                'kode_produk' => 'PRD-018',
                'nama_produk' => 'Sepatu Kasual Pria Kulit',
                'ukuran' => '41',
                'warna' => 'Tan',
                'harga_jual' => 580000.00,
                'stok' => 35,
                'minimum_stok' => 10,
                'bom_category_id' => null,
            ],
            [
                'kode_produk' => 'PRD-019',
                'nama_produk' => 'Sandal Jepit Kulit Pria',
                'ukuran' => '39',
                'warna' => 'Hitam',
                'harga_jual' => 350000.00,
                'stok' => 80,
                'minimum_stok' => 15,
                'bom_category_id' => null,
            ],
            [
                'kode_produk' => 'PRD-020',
                'nama_produk' => 'Sepatu Dinas Kulit Navy',
                'ukuran' => '40',
                'warna' => 'Navy',
                'harga_jual' => 720000.00,
                'stok' => 0,
                'minimum_stok' => 5,
                'bom_category_id' => null,
            ],
        ];

        foreach ($produks as $produk) {
            Produk::create($produk);
        }
    }
}
